spring.application.name=server
server.port=8080
debug=true


# Disable MyBatis mapper locations to avoid scanning
mybatis.mapper-locations=classpath*:mapper/*.xml

# Agent service URL
agent.base-url=http://localhost:8000

# Logging
logging.level.root=INFO
logging.level.com.worm.server=DEBUG
